/*!
 * \file nll_loss_tiling_key.h
 * \brief schMode: 0 half+i32, 1 half+i64, 2 bf16+i32, 3 bf16+i64, 4 fp32+i32, 5 fp32+i64
 */

#ifndef __NLLLOSS_TILING_KEY_H__
#define __NLLLOSS_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define NLLLOSS_TPL_SCH_MODE_0 0
#define NLLLOSS_TPL_SCH_MODE_1 1
#define NLLLOSS_TPL_SCH_MODE_2 2
#define NLLLOSS_TPL_SCH_MODE_3 3
#define NLLLOSS_TPL_SCH_MODE_4 4
#define NLLLOSS_TPL_SCH_MODE_5 5

ASCENDC_TPL_ARGS_DECL(
    NllLoss,
    ASCENDC_TPL_UINT_DECL(
        schMode, 3, ASCENDC_TPL_UI_LIST, NLLLOSS_TPL_SCH_MODE_0, NLLLOSS_TPL_SCH_MODE_1, NLLLOSS_TPL_SCH_MODE_2,
        NLLLOSS_TPL_SCH_MODE_3, NLLLOSS_TPL_SCH_MODE_4, NLLLOSS_TPL_SCH_MODE_5));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(
    schMode, ASCENDC_TPL_UI_LIST, NLLLOSS_TPL_SCH_MODE_0, NLLLOSS_TPL_SCH_MODE_1, NLLLOSS_TPL_SCH_MODE_2,
    NLLLOSS_TPL_SCH_MODE_3, NLLLOSS_TPL_SCH_MODE_4, NLLLOSS_TPL_SCH_MODE_5)));

#endif
